<a href="https://colab.research.google.com/github/Maxxx-VS/IMA_SibADI/blob/main/ML_1_2_%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Задание 1.2 Стандартизация данных и оптимизация параметров модели методом градиентного спуска

In [1]:
# импорты
import numpy as np
import pandas as pd
from scipy import stats
import statsmodels.api as sm
import plotly.graph_objects as go

In [2]:
# загрузка данных
df = pd.read_csv('/content/data_for_regression.csv')

In [3]:
# извлечение x, y
x = df.Me.to_numpy()
y = df.tc.to_numpy()
print("x = ", x, "\n", "y = ", y)

x =  [140 210 252  28  70 140 210 252  28  70 140 210 252  28  70 140 210 252
  28  70 140 210] 
 y =  [80.7 82.8 83.2 79.3 80.2 80.7 83.2 83.7 80.3 80.4 81.5 82.3 84.3 80.2
 80.7 82.1 83.1 85.  80.7 80.8 82.8 83.6]


In [4]:
# стандартизация вручную
x_sc = (x - x.mean()) / x.std()
print(x_sc)

[-0.03929705  0.82523813  1.34395924 -1.42255335 -0.90383224 -0.03929705
  0.82523813  1.34395924 -1.42255335 -0.90383224 -0.03929705  0.82523813
  1.34395924 -1.42255335 -0.90383224 -0.03929705  0.82523813  1.34395924
 -1.42255335 -0.90383224 -0.03929705  0.82523813]


In [5]:
# изменение формы для scikit-learn
x_reshaped = x.reshape(-1, 1)
y_reshaped = y.reshape(-1, 1)

In [6]:
# StandardScaler fit
from sklearn.preprocessing import StandardScaler
xscaler = StandardScaler(with_mean=True, with_std=True)
yscaler = StandardScaler(with_mean=True, with_std=True)
xscaler.fit(x_reshaped)
yscaler.fit(y_reshaped)

StandardScaler()

In [7]:
# transform
x_scaled = xscaler.transform(x_reshaped)
y_scaled = yscaler.transform(y_reshaped)
np.set_printoptions(precision=4)
print("стандартизованные x:\n", x_scaled)
print("стандартизованные y:\n", y_scaled)

стандартизованные x:
 [[-0.0393]
 [ 0.8252]
 [ 1.344 ]
 [-1.4226]
 [-0.9038]
 [-0.0393]
 [ 0.8252]
 [ 1.344 ]
 [-1.4226]
 [-0.9038]
 [-0.0393]
 [ 0.8252]
 [ 1.344 ]
 [-1.4226]
 [-0.9038]
 [-0.0393]
 [ 0.8252]
 [ 1.344 ]
 [-1.4226]
 [-0.9038]
 [-0.0393]
 [ 0.8252]]
стандартизованные y:
 [[-0.7701]
 [ 0.5878]
 [ 0.8465]
 [-1.6753]
 [-1.0934]
 [-0.7701]
 [ 0.8465]
 [ 1.1698]
 [-1.0287]
 [-0.964 ]
 [-0.2528]
 [ 0.2645]
 [ 1.5577]
 [-1.0934]
 [-0.7701]
 [ 0.1352]
 [ 0.7818]
 [ 2.0104]
 [-0.7701]
 [-0.7054]
 [ 0.5878]
 [ 1.1051]]


In [8]:
# обратное преобразование
y_back = yscaler.inverse_transform(y_scaled)
print(y_back)

[[80.7]
 [82.8]
 [83.2]
 [79.3]
 [80.2]
 [80.7]
 [83.2]
 [83.7]
 [80.3]
 [80.4]
 [81.5]
 [82.3]
 [84.3]
 [80.2]
 [80.7]
 [82.1]
 [83.1]
 [85. ]
 [80.7]
 [80.8]
 [82.8]
 [83.6]]


In [9]:
# диаграмма стандартизованных данных
fig1 = go.Figure()
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_back.flatten(),
    mode='markers',
    name='станд. данные',
    marker=dict(color='magenta', size=7),
    opacity=0.8))

fig1.update_layout(
    title_text="Стандартизованные данные",
    title_font_size=20,
    xaxis_title="x стандартизованные",
    yaxis_title="y")
fig1.show()

In [10]:
# МНК на стандартизованных x
X = sm.add_constant(x_scaled)
reg = sm.OLS(y_back, X).fit()
b_ols = reg.params[0]
w_ols = reg.params[1]
print("Оптимальные параметры регрессии (станд. данные): b = %0.4f, w = %0.4f \n" % (b_ols, w_ols))

Оптимальные параметры регрессии (станд. данные): b = 81.8909, w = 1.4198 



In [11]:
# прогноз по модели
y_hat = b_ols + w_ols * x_scaled

In [12]:
# MSE
loss_ols = (reg.resid ** 2).mean()
print("Минимум функции потерь MSE для стандартизованных данных: %0.4f" % loss_ols)

Минимум функции потерь MSE для стандартизованных данных: 0.3760


In [13]:
# визуализация модели МНК
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_hat.flatten(),
    mode='lines+markers',
    name='модель МНК (оптимум b, w)',
    marker=dict(color='green', size=7),
    opacity=0.8))
fig1.show()

In [14]:
# пространство параметров
b_range = np.linspace(b_ols + 4, b_ols - 4, 201)
w_range = np.linspace(w_ols + 4, w_ols - 4, 201)
bs, ws = np.meshgrid(b_range, w_range)
bs.shape, ws.shape

((201, 201), (201, 201))

In [15]:
# все выходы модели на сетке
all_y_hat = np.apply_along_axis(func1d=lambda x: bs + ws * x,
                                axis=1,
                                arr=x_scaled)
all_y_hat.shape

(22, 201, 201)

In [16]:
# именение формы y
y_reshaped = y.reshape(-1, 1, 1)
y_reshaped.shape

(22, 1, 1)

In [17]:
# ошибки
all_errors = all_y_hat - y_reshaped
all_errors.shape

(22, 201, 201)

In [18]:
# MSE на сетке
all_losses = (all_errors ** 2).mean(axis=0)
all_losses.shape

(201, 201)

In [19]:
# контурный график
fig2 = go.Figure()
fig2.add_trace(go.Contour(x=b_range,
                          y=w_range,
                          z=all_losses,
                          contours_coloring='lines',
                          line_width=1,
                          name='MSE',
                          contours=dict(start=0, end=14, size=0.2,
                                        showlabels=True,
                                        labelfont=dict(size=12, color='black')),
                          showlegend=True, showscale=False))

fig2.add_trace(go.Scatter(x=[b_ols], y=[w_ols],
                          mode='markers',
                          name='Оптимальные параметры',
                          marker=dict(color='green', size=7, opacity=0.8),
                          showlegend=True))

fig2.update_layout(title_text="Критерий точности модели: Функция потерь",
                   title_font_size=16,
                   xaxis_title="b", yaxis_title="w")
fig2.update_yaxes(scaleanchor="x", scaleratio=1)
fig2.show()

In [20]:
# поверхность MSE в 3D
fig3 = go.Figure()
fig3.add_trace(go.Scatter3d(x=bs.flatten(), y=ws.flatten(), z=all_losses.flatten(),
                            mode='markers',
                            name='MSE',
                            marker=dict(size=1, color='blue', opacity=0.8)))
fig3.add_trace(go.Scatter3d(x=[b_ols], y=[w_ols], z=[loss_ols],
                            mode='markers',
                            name='Оптимальные параметры',
                            marker=dict(size=7, color='green', opacity=0.8)))
fig3.update_layout(
    scene=dict(xaxis_title='b', yaxis_title='w', zaxis_title='MSE'),
    title_text="Критерий точности модели: Функция потерь",
    title_font_size=16)
fig3.layout.scene.camera.projection.type = "orthographic"
fig3.show()

In [21]:
# стартовые параметры
b0 = 80
w0 = 2

In [22]:
# MSE в стартовой точке
x_reshaped = x_sc.flatten()
y_reshaped = y.flatten()

e = (b0 + w0 * x_reshaped) - y_reshaped
loss = (e ** 2).mean()
print(loss)

4.2882053925763195


In [23]:
# визуализация старта
fig2.add_trace(go.Scatter(x=[b0], y=[w0],
                          mode='markers',
                          name='Старт поиска (b0, w0)',
                          marker=dict(color='red', size=7, opacity=0.8),
                          showlegend=True))
fig2.show()

In [24]:
# градиент
b_grad = 2 * e.mean()
w_grad = 2 * (x_sc * e).mean()
print("Градиент функции потерь: [%0.2f %0.2f]" % (b_grad, w_grad))

Градиент функции потерь: [-3.78 1.16]


In [25]:
# векторы градиента и антиградиента
fig2.add_trace(
    go.Scatter(x=[b0, b0 + b_grad],
               y=[w0, w0 + w_grad],
               name='градиент MSE',
               marker=dict(color='blue', size=7,
                           symbol="arrow-bar-up", angleref="previous"),
               showlegend=True))
fig2.add_trace(
    go.Scatter(x=[b0, b0 - b_grad],
               y=[w0, w0 - w_grad],
               name='антиградиент MSE',
               marker=dict(color='red', size=7,
                           symbol="arrow-bar-up", angleref="previous"),
               showlegend=True))
fig2.show()
lr = 0.2

In [26]:
# шаг 1
b1 = b0 - lr * b_grad
w1 = w0 - lr * w_grad
print("Параметры b и w после шага 1: [%0.2f %0.2f]" % (b1, w1))

Параметры b и w после шага 1: [80.76 1.77]


In [27]:
# MSE после шага 1
e = (b1 + w1 * x_reshaped) - y_reshaped
loss = (e ** 2).mean()
print(loss)

1.784392453448514


In [28]:
# новый градиент после шага 1
b_grad = 2 * e.mean()
w_grad = 2 * (x_sc * e).mean()
print("Градиент функции потерь: [%0.2f %0.2f]" % (b_grad, w_grad))

Градиент функции потерь: [-2.27 0.70]


In [29]:
# визуализация после шага 1
fig2.add_trace(go.Scatter(x=[b1], y=[w1],
                          mode='markers',
                          name='После шага 1: (b1, w1)',
                          marker=dict(color='black', size=7, opacity=0.8),
                          showlegend=True))
fig2.add_trace(
    go.Scatter(x=[b1, b1 - b_grad],
               y=[w1, w1 - w_grad],
               name='антиградиент после шага 1',
               marker=dict(color='black', size=7,
                           symbol="arrow-bar-up", angleref="previous"),
               showlegend=True))
fig2.show()

In [30]:
# модель с параметрами b0, w0
y_hat = b0 + w0 * x_reshaped
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_hat.flatten(),
    mode='lines+markers',
    name='модель с параметрами b0, w0',
    marker=dict(color='red', size=7),
    opacity=0.8))
fig1.show()

In [31]:
# модель с параметрами b1, w1
y_hat = b1 + w1 * x_reshaped
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_hat.flatten(),
    mode='lines+markers',
    name='модель с параметрами b1, w1',
    marker=dict(color='black', size=7),
    opacity=0.8))
fig1.show()

In [32]:
# шаг 2
b2 = b1 - lr * b_grad
w2 = w1 - lr * w_grad
print("Параметры b и w после шага 2: [%0.2f %0.2f]" % (b2, w2))

e = (b2 + w2 * x_reshaped) - y_reshaped
loss2 = (e ** 2).mean()
print("MSE после шага 2:", loss2)

b_grad = 2 * e.mean()
w_grad = 2 * (x_sc * e).mean()
print("Градиент функции потерь: [%0.2f %0.2f]" % (b_grad, w_grad))

fig2.add_trace(go.Scatter(x=[b2], y=[w2],
                          mode='markers',
                          name='После шага 2: (b2, w2)',
                          marker=dict(color='orange', size=7, opacity=0.8),
                          showlegend=True))
fig2.add_trace(
    go.Scatter(x=[b2, b2 - b_grad],
               y=[w2, w2 - w_grad],
               name='антиградиент после шага 2',
               marker=dict(color='orange', size=7,
                           symbol="arrow-bar-up", angleref="previous"),
               showlegend=True))
fig2.show()

y_hat = b2 + w2 * x_reshaped
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_hat.flatten(),
    mode='lines+markers',
    name='модель с параметрами b2, w2',
    marker=dict(color='orange', size=7),
    opacity=0.8))
fig1.show()

Параметры b и w после шага 2: [81.21 1.63]
MSE после шага 2: 0.8830197953624966
Градиент функции потерь: [-1.36 0.42]


In [33]:
# шаг 3
b3 = b2 - lr * b_grad
w3 = w2 - lr * w_grad
print("Параметры b и w после шага 3: [%0.2f %0.2f]" % (b3, w3))

e = (b3 + w3 * x_reshaped) - y_reshaped
loss3 = (e ** 2).mean()
print("MSE после шага 3:", loss3)

b_grad = 2 * e.mean()
w_grad = 2 * (x_sc * e).mean()
print("Градиент функции потерь: [%0.2f %0.2f]" % (b_grad, w_grad))

fig2.add_trace(go.Scatter(x=[b3], y=[w3],
                          mode='markers',
                          name='После шага 3: (b3, w3)',
                          marker=dict(color='purple', size=7, opacity=0.8),
                          showlegend=True))
fig2.add_trace(
    go.Scatter(x=[b3, b3 - b_grad],
               y=[w3, w3 - w_grad],
               name='антиградиент после шага 3',
               marker=dict(color='purple', size=7,
                           symbol="arrow-bar-up", angleref="previous"),
               showlegend=True))
fig2.show()

y_hat = b3 + w3 * x_reshaped
fig1.add_trace(go.Scatter(
    x=x_scaled.flatten(),
    y=y_hat.flatten(),
    mode='lines+markers',
    name='модель с параметрами b3, w3',
    marker=dict(color='purple', size=7),
    opacity=0.8))
fig1.show()

Параметры b и w после шага 3: [81.48 1.55]
MSE после шага 3: 0.5585256384515211
Градиент функции потерь: [-0.82 0.25]


In [35]:
# сравнение с оптимумом
print("Сравнение с оптимальными значениями (МНК):")
print("Оптимум OLS:     b = %0.4f, w = %0.4f, MSE = %0.4f" % (b_ols, w_ols, loss_ols))
print("После шага 1:    b = %0.4f, w = %0.4f, MSE = %0.4f" % (b1, w1, loss))
print("После шага 2:    b = %0.4f, w = %0.4f, MSE = %0.4f" % (b2, w2, loss2))
print("После шага 3:    b = %0.4f, w = %0.4f, MSE = %0.4f" % (b3, w3, loss3))
print("Вывод: после стандартизации x градиентный спуск быстро сходится к оптимуму.")

Сравнение с оптимальными значениями (МНК):
Оптимум OLS:     b = 81.8909, w = 1.4198, MSE = 0.3760
После шага 1:    b = 80.7564, w = 1.7679, MSE = 1.7844
После шага 2:    b = 81.2102, w = 1.6287, MSE = 0.8830
После шага 3:    b = 81.4825, w = 1.5451, MSE = 0.5585
Вывод: после стандартизации x градиентный спуск быстро сходится к оптимуму.
